```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = "hide")
library(tidyverse)
library(here)
library(debugr)
```

```{r}
#Setting constraint boundary
#t <- 14 # number of daily timesteps for 14 days
#r <- 3 # number of reservoirs = 3 
Storage_min <- c(0, 0, 0) 
Storage_max <- c(2814.3, 71.2, 130)
Forebay_min <- c(1208, 733, 334)
Forebay_max <- c(1295, 738, 342)
Energy_min <- c(0, 0, 250)
Energy_max <- c(6735, 930, 1120)
Fb_target <- 1281 
```

```{r}
devtools::load_all()
```


```{r}
#This function calls all the constraints validation function from R and return a list of data where if value >= 0 means the constraint is satisfied and if value <0 means constraint is violated
Constraints_validation <- function(mean_sd_simulations, Storage_min, Storage_max, Forebay_min, Forebay_max, Energy_min, Energy_max, Fb_target, rel_index, r, t){
  
  Storage_constraints_validation <- Storage_constraints(mean_sd_simulations, Storage_min, Storage_max, rel_index, r, t) 
  
  Forebay_constraints_validation <- Forebay_constraints(mean_sd_simulations, Forebay_min, Forebay_max, rel_index, r, t)
  Energy_constraints_validation <- Energy_constraints(mean_sd_simulations, Energy_min, Energy_max, rel_index, r, t) 
  
  ForebayEndofPeriod_constraints_validation <- ForebayEndofPeriod_constraints(mean_sd_simulations, Fb_target, rel_index, r, t)
  
  Constraints_validation <- list("Storage_constraints" = Storage_constraints_validation, "Forebay_constraints" = Forebay_constraints_validation, "Energy_constraints" = Energy_constraints_validation, "Forebay_EOP_Constraints" = ForebayEndofPeriod_constraints_validation)
  
}
```

```{r}
Constraints_validation_data <- Constraints_validation(mean_sd_simulations, Storage_min, Storage_max, Forebay_min, Forebay_max, Energy_min, Energy_max, Fb_target, rel_index=0.9, r=3, t=14)
```