```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = "hide")
library(tidyverse)
library(here)
library(debugr)
```

**Simulations for Quantifying Storage, Forebay Elevation, Tailwater Elevation, Head and Energy**
```{r}
#Setting initial conditions
#t <- 14 # number of daily timesteps for 14 days
#r <- 3 # number of reservoirs = 3 
Current_Inflows <- c(81.45, 11.04, 131.27) 
Current_Outflows <- c(55.72, 13.54, 127.03)
Current_Storage <- c(2260, 47.8, 79.1)
Current_Forebay <- c(1280.9, 735.93, 339.14)
Current_Tailwater <- c(957.46, 636.41, 265.03)
Outflows_lb <- c(1.13, 8.2, 7)
Outflows_ub <- c(294.04, 150, 214.2) 
Fb_coeff <- matrix(c(-3.63e-6, 0.0406, 1208, -3.6467e-4, 0.2689, 724, 0, 0.0571, 334.5), nrow = 3, ncol = 3, byrow = TRUE)
Tw_coeff <- matrix(c(447.97, 122.81, 18.60, 0.0910, 0.0210, 0.0202, 0.5286, 0.8060, 0.9234), nrow = 3, ncol = 3, byrow = TRUE)
#Will add more
```

```{r}
#Generating random outflows between upper and lower bound. This part is temporary as when we code the optimization part, this data will be generated from the optimization algorithm.

#Assuming uniform distribution
#sample_matrix <- runif(n = 3*14) %>% matrix(ncol = 14)
#lb <- rep(Outflows_lb, 14) %>% matrix(nrow=3)
#ub <- rep(Outflows_ub, 14) %>% matrix(nrow=3)
#Outflows <- lb + sample_matrix*ub
#Outflows
```

```{r}

# Sampling Inflows data realizations 

GCLInflowsdata_Mean <- rowMeans(GCLInflowsdata[,2:28])
LWGInflowsdata_Mean <- rowMeans(LWGInflowsdata[,2:28])
#GCLInflowsdata_Mean
#LWGInflowsdata_Mean
ntimes <- 10000

GCLInflowsdata_samples <- sample(GCLInflowsdata_Mean, length(GCLInflowsdata_Mean)*ntimes,  replace = TRUE) %>% matrix(nrow = ntimes)

LWGInflowsdata_samples <- sample(LWGInflowsdata_Mean, length(LWGInflowsdata_Mean)*ntimes,  replace = TRUE) %>% matrix(nrow = ntimes)
```

```{r}
# Quantifying storage

Storage_realizations <- function(Inflow1, Inflow2, Storage_initial, Inflow_initial, Outflow_initial, Outflows, delta_t, t, n){
  GCLInflowsdata_samples <- Inflow1
  LWGInflowsdata_samples <- Inflow2
  V_in <- Storage_initial
  I_in <- Inflow_initial
  Q_in <- Outflow_initial
  Q_GCL <- Outflows[1, ]
  Q_LWG <- Outflows[2, ]
  Q_MCN <- Outflows[3, ]
  MCNInflows <- Outflows[1, ] + Outflows[2, ]
  Storage_realizations_GCL <- matrix(0L, nrow =n, ncol = t)
  Storage_realizations_LWG <- matrix(0L, nrow =n, ncol = t)
  Storage_realizations_MCN <- matrix(0L, nrow =1, ncol = t)
 #1st timestep
     Storage_realizations_GCL[, 1] <- ((I_in[1] + GCLInflowsdata_samples[, 1])*0.5) + ((Q_in[1] + Q_GCL[1])*0.5)*delta_t + V_in[1]
 
     Storage_realizations_LWG[, 1] <- ((I_in[2] + LWGInflowsdata_samples[, 1])*0.5 + (Q_in[2] + Q_LWG[1])*0.5)*delta_t + V_in[2]
     
     Storage_realizations_MCN[, 1] <- ((I_in[3] + MCNInflows[1])*0.5 + (Q_in[3] + Q_MCN[1])*0.5)*delta_t + V_in[3]
     
#Rest of the timesteps
     
     for (i in 2:t){
       Storage_realizations_GCL[, i] <- ((GCLInflowsdata_samples[, i-1] + GCLInflowsdata_samples[, i])*0.5 + (Q_GCL[i-1] + Q_GCL[i])*0.5)*delta_t +Storage_realizations_GCL[, i-1]
       
       Storage_realizations_LWG[, i] <- ((LWGInflowsdata_samples[, i-1] + LWGInflowsdata_samples[, i])*0.5 + (Q_LWG[i-1] + Q_LWG[i])*0.5)*delta_t +Storage_realizations_LWG[, i-1]
       
       Storage_realizations_MCN[i] <- ((MCNInflows[i-1] + MCNInflows[i])*0.5 + (Q_MCN[i-1] + Q_MCN[i])*0.5)*delta_t +Storage_realizations_MCN[i-1]
     }
     
     Storage_realizations <- rbind(Storage_realizations_GCL, Storage_realizations_LWG, Storage_realizations_MCN)
  
}

```
```{r}
#Storage_largerealizations <- Storage_realizations(GCLInflowsdata_samples, LWGInflowsdata_samples, Current_Storage, Current_Inflows, Current_Outflows, Outflows, delta_t = 1, t=14, ntimes)

```



```{r}
#Quantifying Forebay Elevation

Forebay_realizations <- function(Storage_largerealizations, Fb_coeff, t, n){
  Storage_realizations_GCL <- Storage_largerealizations[1:n,]
  Storage_realizations_LWG <- Storage_largerealizations[(n+1):(2*n),]
  Storage_realizations_MCN <- Storage_largerealizations[(2*n)+1,]
  Forebay_realizations_GCL <- matrix(0L, nrow =n, ncol = t)
  Forebay_realizations_LWG <- matrix(0L, nrow =n, ncol = t)
  Forebay_realizations_MCN <- matrix(0L, nrow =1, ncol = t)
  
  Forebay_realizations_GCL <- Fb_coeff[1,1]* Storage_realizations_GCL^2 + Fb_coeff[1,2]* Storage_realizations_GCL + Fb_coeff[1,3]
  
  Forebay_realizations_LWG <- Fb_coeff[2,1]* Storage_realizations_LWG^2 + Fb_coeff[2,2]* Storage_realizations_LWG + Fb_coeff[2,3]
  
  Forebay_realizations_MCN <- Fb_coeff[3,1]* Storage_realizations_MCN^2 + Fb_coeff[3,2]* Storage_realizations_MCN + Fb_coeff[3,3]
  
   Forebay_realizations <- rbind(Forebay_realizations_GCL, Forebay_realizations_LWG, Forebay_realizations_MCN)
}


```

```{r}
#Forebay_largerealizations <- Forebay_realizations(Storage_largerealizations, Fb_coeff, t=14, ntimes)

```


```{r}

#Quantifying Tailwater

Tailwater_realizations <- function(Forebay_largerealizations, Outflow_initial, Forebay_initial, Tailwater_initial, Tw_coeff, Outflows, t, n){
 
  Q_GCL <- Outflows[1, ]
  Q_LWG <- Outflows[2, ]
  Q_MCN <- Outflows[3, ]
  Q_in <- Outflow_initial
  Fb_in <- Forebay_initial
  Tw_in <- Tailwater_initial
  Tailwater_realizations_GCL <- matrix(0L, nrow =n, ncol = t)
  Tailwater_realizations_LWG <- matrix(0L, nrow =n, ncol = t)
  Tailwater_realizations_MCN <- matrix(0L, nrow =1, ncol = t)
  
   #1st timestep
     Tailwater_realizations_GCL[, 1] <- Tw_coeff[1,1] + Tw_coeff[2,1]*Q_GCL[1] +Tw_coeff[3,1]*Fb_in[3]
 
     Tailwater_realizations_LWG[, 1] <- Tw_coeff[1,2] + Tw_coeff[2,2]*Q_LWG[1] +Tw_coeff[3,2]*Fb_in[3]
     
     Tailwater_realizations_MCN[, 1] <- Tw_coeff[1,3] + Tw_coeff[2,3]*Tw_in[3] +Tw_coeff[3,3]*(Q_MCN[1] - Q_in[3])
     
     
     #Rest of the timestep
     
     for (i in 2:t){
       Tailwater_realizations_GCL[, i] <- Tw_coeff[1,1] + Tw_coeff[2,1]*Q_GCL[i] + Tw_coeff[3,1]*Forebay_largerealizations[(2*n)+1, i-1]
       
       Tailwater_realizations_LWG[, i] <- Tw_coeff[1,2] + Tw_coeff[2,2]*Q_LWG[i] + Tw_coeff[3,2]*Forebay_largerealizations[(2*n)+1, i-1]
       
       Tailwater_realizations_MCN[, i] <- Tw_coeff[1,3] + Tw_coeff[2,3]*Tailwater_realizations_MCN[, i-1] +Tw_coeff[3,3]*(Q_MCN[i] - Q_MCN[i-1])
     }
  
     Tailwater_realizations <- rbind(Tailwater_realizations_GCL, Tailwater_realizations_LWG, Tailwater_realizations_MCN)
}
```

```{r}
#Tailwater_largerealizations <- Tailwater_realizations(Forebay_largerealizations, Current_Outflows, Current_Forebay, Current_Tailwater, Tw_coeff, Outflows, t=14, ntimes)
```

```{r}
#Quantifying Head

Head_realizations <- function(Forebay_largerealizations, Tailwater_largerealizations){
  
  Head_realizations <- Forebay_largerealizations - Tailwater_largerealizations
}

```

```{r}
#Head_largerealizations <- Head_realizations(Forebay_largerealizations, Tailwater_largerealizations)

```

```{r}
#Quantifying Energy

Energy_realizations <- function(Head_largerealizations, Outflows, efficieny, n){
  e <- efficieny
  Q_GCL <- Outflows[1, ] %>% rep(n) %>% matrix(nrow = n, byrow = TRUE)
  Q_LWG <- Outflows[2, ] %>% rep(n) %>% matrix(nrow = n, byrow = TRUE)
  Q_MCN <- Outflows[3, ]
  Q_out <- rbind(Q_GCL, Q_LWG, Q_MCN) 
  g <- 9.81
  Energy_realizations <- e*Head_largerealizations*0.3048*Q_out*28.31684*g*10^-3
}

```
```{r}
#Energy_largerealizations <- Energy_realizations(Head_largerealizations, Outflows, efficieny= 0.75, ntimes)

```

```{r}
#Quantifying mean and standard deviation for the QoI
mean_sd_sim <- function(Inflow1, Inflow2, Storage_initial, Inflow_initial, Outflow_initial,  Forebay_initial, Tailwater_initial, Outflows, Fb_coeff, Tw_coeff, delta_t, efficieny, t, r, n_samples){
  
  Storage_largerealizations <- Storage_realizations(GCLInflowsdata_samples, LWGInflowsdata_samples, Current_Storage, Current_Inflows, Current_Outflows, Outflows, delta_t, t, n_samples)
  
  Forebay_largerealizations <- Forebay_realizations(Storage_largerealizations, Fb_coeff, t, n_samples)
  
  Tailwater_largerealizations <- Tailwater_realizations(Forebay_largerealizations, Current_Outflows, Current_Forebay, Current_Tailwater, Tw_coeff, Outflows, t, n_samples)
  
  Head_largerealizations <- Head_realizations(Forebay_largerealizations, Tailwater_largerealizations)
  
  Energy_largerealizations <- Energy_realizations(Head_largerealizations, Outflows, efficieny, n_samples)
  n <- n_samples
  
  Storage_mean <- matrix(0L, nrow =r, ncol = t)
  Storage_mean2 <- matrix(0L, nrow =r, ncol = t)
  Forebay_mean <- matrix(0L, nrow =r, ncol = t)
  Forebay_mean2 <- matrix(0L, nrow =r, ncol = t)
  Energy_mean <- matrix(0L, nrow =r, ncol = t)
  Energy_mean2 <- matrix(0L, nrow =r, ncol = t)
  
  Storage_mean[1, ] <- colMeans(Storage_largerealizations[1:n, ])
  Storage_mean[2, ] <- colMeans(Storage_largerealizations[(n+1):(2*n), ])
  Storage_mean[3, ] <- (Storage_largerealizations[(2*n)+1, ])
  Storage_mean2[1, ] <- colMeans(Storage_largerealizations[1:n, ]^2)
  Storage_mean2[2, ] <- colMeans(Storage_largerealizations[(n+1):(2*n), ]^2)
  Storage_mean2[3, ] <- (Storage_largerealizations[(2*n)+1, ]^2)
  
  Storage_sd <- sqrt(Storage_mean2 - (Storage_mean^2))
    
  Forebay_mean[1, ] <- colMeans(Forebay_largerealizations[1:n, ])
  Forebay_mean[2, ] <- colMeans(Forebay_largerealizations[(n+1):(2*n), ])
  Forebay_mean[3, ] <- (Forebay_largerealizations[(2*n)+1, ])
  Forebay_mean2[1, ] <- colMeans(Forebay_largerealizations[1:n, ]^2)
  Forebay_mean2[2, ] <- colMeans(Forebay_largerealizations[(n+1):(2*n), ]^2)
  Forebay_mean2[3, ] <- (Forebay_largerealizations[(2*n)+1, ]^2)
  
  Forebay_sd <- sqrt(Forebay_mean2 - (Forebay_mean^2))

  Energy_mean[1, ] <- colMeans(Energy_largerealizations[1:n, ])
  Energy_mean[2, ] <- colMeans(Energy_largerealizations[(n+1):(2*n), ])
  Energy_mean[3, ] <- (Energy_largerealizations[(2*n)+1, ])
  Energy_mean2[1, ] <- colMeans(Energy_largerealizations[1:n, ]^2)
  Energy_mean2[2, ] <- colMeans(Energy_largerealizations[(n+1):(2*n), ]^2)
  Energy_mean2[3, ] <- (Energy_largerealizations[(2*n)+1, ]^2)
  
  Energy_sd <- sqrt(Energy_mean2 - (Energy_mean^2))
  
  mean_sim <- rbind(Storage_mean, Forebay_mean, Energy_mean)
  sd_sim <- rbind(Storage_sd, Forebay_sd, Energy_sd)
  
  mean_sd_sim <- list("Means" = mean_sim, "Std dev" = sd_sim, "Storage realizations" = Storage_largerealizations, "Forebay realizations" = Forebay_largerealizations, "Tailwater realizations" = Tailwater_largerealizations, "Head realizations" = Head_largerealizations, "Energy_realizations" = Energy_largerealizations)
}


```


```{r}
#Returns a large list of realizations of Storage, Forebay elevation, Tailwater, Head, Energy with the resepctive means and standard deviations of those Quantity of Interest for each reservoirs. This is required to validate the constraints and evaluate the objective functions in the Robust optimization model

# r =3 is the number of reservoirs
# t =14 is the daily timestep for 14 days optimization period
# ntimes =10000 (Atleast for MC) is the number of simulations
#Outflows is the sample outflow or the starting point in the optimization

Outflows <- c(55.72, 13.54, 127.03) %>% rep(14) %>% matrix(ncol = 14)

mean_sd_simulations <- mean_sd_sim(GCLInflowsdata_samples, LWGInflowsdata_samples, Current_Storage, Current_Inflows, Current_Outflows, Current_Forebay, Current_Tailwater, Outflows, Fb_coeff, Tw_coeff, delta_t=1, efficieny=0.75, t=14, r=3, ntimes)

```
```{r}
   #Runtime experiment
    bench::mark(
      chunk_1 = {
        #10000 samples for MC approach
        GCLInflowsdata_Mean <- rowMeans(GCLInflowsdata[,2:28])
LWGInflowsdata_Mean <- rowMeans(LWGInflowsdata[,2:28])

ntimes <- 10000

GCLInflowsdata_samples <- sample(GCLInflowsdata_Mean, length(GCLInflowsdata_Mean)*ntimes,  replace = TRUE) %>% matrix(nrow = ntimes)

LWGInflowsdata_samples <- sample(LWGInflowsdata_Mean, length(LWGInflowsdata_Mean)*ntimes,  replace = TRUE) %>% matrix(nrow = ntimes)
        mean_sd_sim(GCLInflowsdata_samples, LWGInflowsdata_samples, Current_Storage, Current_Inflows, Current_Outflows, Current_Forebay, Current_Tailwater, Outflows, Fb_coeff, Tw_coeff, delta_t=1, efficieny=0.75, t=14, r=3, ntimes)
      },
      chunk_2 = {
         #1000 samples for MC approach
           GCLInflowsdata_Mean <- rowMeans(GCLInflowsdata[,2:28])
LWGInflowsdata_Mean <- rowMeans(LWGInflowsdata[,2:28])

ntimes <- 1000

GCLInflowsdata_samples <- sample(GCLInflowsdata_Mean, length(GCLInflowsdata_Mean)*ntimes,  replace = TRUE) %>% matrix(nrow = ntimes)

LWGInflowsdata_samples <- sample(LWGInflowsdata_Mean, length(LWGInflowsdata_Mean)*ntimes,  replace = TRUE) %>% matrix(nrow = ntimes)
        
        mean_sd_sim(GCLInflowsdata_samples, LWGInflowsdata_samples, Current_Storage, Current_Inflows, Current_Outflows, Current_Forebay, Current_Tailwater, Outflows, Fb_coeff, Tw_coeff, delta_t=1, efficieny=0.75, t=14, r=3, ntimes)
        }
      ,
      check = FALSE  # if you don't expect the output to be identical
    )
```